### ISSUE TITLE
Bioboxes GUI should use docker-java

### ISSUE THREAD

**Issue by pbelmann** [staynerzone/BioboxSITBSources#3]
I recommend using the docker-java library:

https://github.com/docker-java/docker-java

It allows us to create/control/terminate/log container directly in java without using system calls:

https://github.com/staynerzone/BioboxSITBSources/blob/master/Sources/SITB/src/main/java/org/bioboxes/sitb/controller/SessionController.java#L120-L127

**Comment by staynerzone** [comment]
I'll try that! 
Thank you for this issue, but in my opinion, there is no need of a docker-control-mechanism, isn't it?
We will just start our assembler-boxes once. I'm afraid of taking too much libraries for a simple exec command.

Furthermore I do need the stdout for the JSF-panel. II'll hope this possible with the docker-api, too.
But I'll surely try this out!

Best regards

**Comment by pbelmann** [comment]
> Thank you for this issue, but in my opinion, there is no need of a docker-control-mechanism, isn't it?
We will just start our assembler-boxes once. I'm afraid of taking too much libraries for a simple exec command.

I agree at the moment we don't have many use cases. But on the long term we could integrate mechanisms like: 

* cancellation of a container 

* starting multiple containers

* get report of a container run (docker inspect)

* checking for tags in docker hub

* ....

This is all possible in docker-java. 

> Furthermore I do need the stdout for the JSF-panel. II'll hope this possible with the docker-api, too.

Yes it's possible. I'm using it in one of my projects.

> But I'll surely try this out!

Thanks!
