### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by pbelmann** [staynerzone/BioboxSITBSources#8]
This project should follow the responsive design principle.

I suggest one of the following frameworks:

* [Bootstrap](http://getbootstrap.com/)

* [Foundation](http://foundation.zurb.com/)

@staynerzone already suggested to use bootstrap in combination with primefaces which would be great.

I think one team member can just create a branch and already start experimenting with this. 

Maybe @staynerzone can post his experience with bootstrap in combination with primefaces in this thread?

**Comment by maximseitz** [comment]
Already started a layout branch, pushing in a few moments and start experimenting with bootstrap in combination with primefaces

**Comment by pbelmann** [comment]
nice

**Comment by maximseitz** [comment]
On the feature/layout branch I tried a the [BootsFaces](http://bootsfaces.net "BootsFaces") JSF framework to integrate some responsivness. Still a bit hardcoded but on the right way I guess. 
Need feedback if its ok using this framework
